### ISSUE TITLE
cant build 

### ISSUE THREAD

**Issue by Artturin** [sudormrfbin/octerm#16]
hi i updated my pin of this package and cant build because of this path usage https://github.com/sudormrfbin/octerm/blob/98148721a4fe7226c19dd8d87ee032e0dbf2f4ea/Cargo.toml#L19

**Comment by sudormrfbin** [comment]
`meow` was (is?) an experimental TUI framework that I was working on, and I was using octerm to prototype it's features. I've since shifted the UI from a TUI to a REPL, so it doesn't depend on `meow` anymore.
